In [55]:
import numpy as np

print('\n---------making an numpy array-----------\n')
arr = np.array((1,2,3,4,5)) #array from tuple
arr1 = np.array([1,2,3,4,5]) #array from list
print(arr)
print(arr1)
print(type(arr)) # to find type of numpy array object

print('\n-------------Creating a 2-D array from a list of lists-------------\n')
arr_2d = np.array([[1,2,3],[2,3,4],[5,6,7]])
print(arr_2d)
print(type(arr_2d))

print('\n--------------Creating a 3-D array from a list of lists-------------\n')
arr_3d = np.array([[[1,2,4],[2,3,4]],[[1,2,4],[2,3,4]]])
print(arr_3d)
print(type(arr_3d))

print('\n-------------array can be converted to any other valid data type------------\n')
arr_float = np.array(arr_2d,dtype = float)
print(arr_float)
print(type(arr_float))

print('\n-------------NumPy tries to find a common datatype that can accommodate all the elements----------------\n')
arrMixEl = np.array(['a',2.3,5,40000])
print(arrMixEl)

print('\n-------------If you want to maintain the original datatype , we can explicit specify the datatype-----------\n')
arrMixEl1 = np.array(['a',2.3,5,40000],dtype=object)
print(arrMixEl1)

print('\n-------------find the dimension of array----------------\n')
print('Dimension of Array = ' ,arr_3d.ndim)

print('\n-------------find the shape of array----------------\n')
print('Shape of Array = ', arr_3d.shape)

print('\n----------The ndarray.dtype attribute in NumPy represents the datatype of the elements contained within the array----\n')
print(arrMixEl,arrMixEl.dtype)
print(arrMixEl1,arrMixEl1.dtype)
print(arr,arr.dtype)

print('\n---------------The ndarray.itemsize represents the size in bytes of each element in the array.It provides how much menmory each element occupies based on its datatype-------------\n')
print(arr.itemsize)
print(arrMixEl.itemsize)

print('\n----------The ndarray.data provides a direct buffer to the memory location where the array''s data is stored-----------\n')
print(arr.data)
print(arr_3d.data)

print('\n-----------------Slicing in numpy Array-------------------------\n')

arrF = [1,2,3,4,5,6,7,8,9]
arrS1 = arrF[3:6] #3rd element to fourth element
arrS2 = arrF[::2] #iterates through all element and takes the 1st element then skips one then takes one and so on
print(arrS1)
print(arrS2)

arrF_2d = np.array([[1,2,3,4],[4,5,6,7],[8,9,10,11],[12,13,14,15]])
print('Full 2d array  ',arrF_2d)
sliced2dArray = arrF_2d[1:3,1:3] #It starts from 1st row and goes till 2nd row and starts from 1st column and goes to second column
print('Sliced Array ',sliced2dArray)

print('\n----------------Arithmetic operations------------------\n')#element wise
lis1 = np.array([1,2,3,4])
lis2 = np.array([5,6,7,8])

print('Addition' ,lis1+lis2)
print('Substraction' ,lis1-lis2)
print('Division' ,lis1/lis2)



---------making an numpy array-----------

[1 2 3 4 5]
[1 2 3 4 5]
<class 'numpy.ndarray'>

-------------Creating a 2-D array from a list of lists-------------

[[1 2 3]
 [2 3 4]
 [5 6 7]]
<class 'numpy.ndarray'>

--------------Creating a 3-D array from a list of lists-------------

[[[1 2 4]
  [2 3 4]]

 [[1 2 4]
  [2 3 4]]]
<class 'numpy.ndarray'>

-------------array can be converted to any other valid data type------------

[[1. 2. 3.]
 [2. 3. 4.]
 [5. 6. 7.]]
<class 'numpy.ndarray'>

-------------NumPy tries to find a common datatype that can accommodate all the elements----------------

['a' '2.3' '5' '40000']

-------------If you want to maintain the original datatype , we can explicit specify the datatype-----------

['a' 2.3 5 40000]

-------------find the dimension of array----------------

Dimension of Array =  3

-------------find the shape of array----------------

Shape of Array =  (2, 2, 3)

----------The ndarray.dtype attribute in NumPy represents the datatype of the el

In [93]:
import numpy as np
print('\n-------------Transpose--------------\n')
arr3d = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
print('Original array \n',arr3d)
arr3dtr = arr3d.transpose()
print('Transposed array using transpose() method \n',arr3dtr)
arr3dT = arr3d.T
print('Transposed array using Transpose attribute \n',arr3dT)
print('\n-------------Sorting--------------\n')
print('Axis = -1 sorts the array inplace, It does not create a copy of the array')
arr = np.array((1,2,5,3,10,4,5))
sorted_array = np.sort(arr,axis=-1)
print(sorted_array)
print('Axis = 0 Operations along this axis will operate along column \n Axis = 1 Operations along this axis will operate along rows\n')
arr2d = np.array([[1,2,30,4],[50,6,7,8],[9,100,11,12]])
print('original 2d array \n' ,arr2d)
arrSort1Axis = np.sort(arr2d,axis=1)
print('Array sorted along 1 axis \n',arrSort1Axis)
arrSort0Axis = np.sort(arr2d,axis=0)
print('Array sorted along 0 axis \n',arrSort0Axis)

print('\n np.argsort Return the indices that will sort the array')
print('Original array \n', arr)
print('Indices that would sort the array ', np.argsort(arr))

print('\n --------------Concatenate----------- \n')
arr11 = np.array((1,2,3))
arr21 = np.array((4,5,6))
res = np.concatenate((arr11,arr21)) # when using concatanate it should be in tuple
print('Concatenated Array ',res)

print('\n We can choose which axis to concatenate \n')
arr2d1 = [[1,2,3],[4,5,6]]
arr2d2 = [[8,6,5],[3,5,9]]
print('Along 0 axis')
res = np.concatenate((arr2d1,arr2d2),axis = 0)
print(res)
print('Along 1 axis')
res = np.concatenate((arr2d1,arr2d2),axis = 1)
print(res)

print('\n--------------Reshape--------------\n')
arr = np.array([1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18])
print('Original array \n',arr)
arreshaped2d = arr.reshape(3,6)
arreshaped3d = arr.reshape(3,3,2)
print('Reshaped 2d Array \n',arreshaped2d)
print('Reshaped 3d Array \n',arreshaped3d)
print('Back to flattened array')
print(arreshaped2d.reshape(-1))
print(arreshaped3d.reshape(-1))


-------------Transpose--------------

Original array 
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
Transposed array using transpose() method 
 [[ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]
 [ 4  8 12]]
Transposed array using Transpose attribute 
 [[ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]
 [ 4  8 12]]

-------------Sorting--------------

Axis = -1 sorts the array inplace, It does not create a copy of the array
[ 1  2  3  4  5  5 10]
Axis = 0 Operations along this axis will operate along column 
 Axis = 1 Operations along this axis will operate along rows

original 2d array 
 [[  1   2  30   4]
 [ 50   6   7   8]
 [  9 100  11  12]]
Array sorted along 1 axis 
 [[  1   2   4  30]
 [  6   7   8  50]
 [  9  11  12 100]]
Array sorted along 0 axis 
 [[  1   2   7   4]
 [  9   6  11   8]
 [ 50 100  30  12]]

 np.argsort Return the indices that will sort the array
Original array 
 [ 1  2  5  3 10  4  5]
Indices that would sort the array  [0 1 3 5 2 6 4]

 --------------Concatenate----------- 

Concatenated 

In [98]:
import numpy as np
print('\n---------Statistical methods--------------\n')
arr = np.array([[1, 2, 3],[4, 5, 6]])
print('Original Array \n',arr)
mean_all = np.mean(arr) # Mean of all elements
print('mean of all element: ',mean_all)
mean_axis0 = np.mean(arr, axis=0) # Mean along axis 0 (columns)
print('mean along axis 0: ',mean_axis0)
mean_axis1 = np.mean(arr, axis=1) # Mean along axis 1 (rows)
print('mean along axis 1: ',mean_axis1)

median_all = np.median(arr) # Median of all elements
median_axis0 = np.median(arr, axis=0) # Median along axis 0
median_axis1 = np.median(arr, axis=1) # Median along axis 1
print("Median of all elements:", median_all)
print("Median along axis 0:", median_axis0)
print("Median along axis 1:", median_axis1)

std_all = np.std(arr) # Standard deviation of all elements
std_axis0 = np.std(arr, axis=0) # Standard deviation along axis 0
std_axis1 = np.std(arr, axis=1) # Standard deviation along axis 1
print("Standard deviation of all elements:", std_all)
print("Standard deviation along axis 0:", std_axis0)
print("Standard deviation along axis 1:", std_axis1)


---------Statistical methods--------------

Original Array 
 [[1 2 3]
 [4 5 6]]
mean of all element:  3.5
mean along axis 0:  [2.5 3.5 4.5]
mean along axis 1:  [2. 5.]
Median of all elements: 3.5
Median along axis 0: [2.5 3.5 4.5]
Median along axis 1: [2. 5.]
Standard deviation of all elements: 1.707825127659933
Standard deviation along axis 0: [1.5 1.5 1.5]
Standard deviation along axis 1: [0.81649658 0.81649658]
