In [55]:
import numpy as np

print('\n---------making an numpy array-----------\n')
arr = np.array((1,2,3,4,5)) #array from tuple
arr1 = np.array([1,2,3,4,5]) #array from list
print(arr)
print(arr1)
print(type(arr)) # to find type of numpy array object

print('\n-------------Creating a 2-D array from a list of lists-------------\n')
arr_2d = np.array([[1,2,3],[2,3,4],[5,6,7]])
print(arr_2d)
print(type(arr_2d))

print('\n--------------Creating a 3-D array from a list of lists-------------\n')
arr_3d = np.array([[[1,2,4],[2,3,4]],[[1,2,4],[2,3,4]]])
print(arr_3d)
print(type(arr_3d))

print('\n-------------array can be converted to any other valid data type------------\n')
arr_float = np.array(arr_2d,dtype = float)
print(arr_float)
print(type(arr_float))

print('\n-------------NumPy tries to find a common datatype that can accommodate all the elements----------------\n')
arrMixEl = np.array(['a',2.3,5,40000])
print(arrMixEl)

print('\n-------------If you want to maintain the original datatype , we can explicit specify the datatype-----------\n')
arrMixEl1 = np.array(['a',2.3,5,40000],dtype=object)
print(arrMixEl1)

print('\n-------------find the dimension of array----------------\n')
print('Dimension of Array = ' ,arr_3d.ndim)

print('\n-------------find the shape of array----------------\n')
print('Shape of Array = ', arr_3d.shape)

print('\n----------The ndarray.dtype attribute in NumPy represents the datatype of the elements contained within the array----\n')
print(arrMixEl,arrMixEl.dtype)
print(arrMixEl1,arrMixEl1.dtype)
print(arr,arr.dtype)

print('\n---------------The ndarray.itemsize represents the size in bytes of each element in the array.It provides how much menmory each element occupies based on its datatype-------------\n')
print(arr.itemsize)
print(arrMixEl.itemsize)

print('\n----------The ndarray.data provides a direct buffer to the memory location where the array''s data is stored-----------\n')
print(arr.data)
print(arr_3d.data)

print('\n-----------------Slicing in numpy Array-------------------------\n')

arrF = [1,2,3,4,5,6,7,8,9]
arrS1 = arrF[3:6] #3rd element to fourth element
arrS2 = arrF[::2] #iterates through all element and takes the 1st element then skips one then takes one and so on
print(arrS1)
print(arrS2)

arrF_2d = np.array([[1,2,3,4],[4,5,6,7],[8,9,10,11],[12,13,14,15]])
print('Full 2d array  ',arrF_2d)
sliced2dArray = arrF_2d[1:3,1:3] #It starts from 1st row and goes till 2nd row and starts from 1st column and goes to second column
print('Sliced Array ',sliced2dArray)

print('\n----------------Arithmetic operations------------------\n')#element wise
lis1 = np.array([1,2,3,4])
lis2 = np.array([5,6,7,8])

print('Addition' ,lis1+lis2)
print('Substraction' ,lis1-lis2)
print('Division' ,lis1/lis2)



---------making an numpy array-----------

[1 2 3 4 5]
[1 2 3 4 5]
<class 'numpy.ndarray'>

-------------Creating a 2-D array from a list of lists-------------

[[1 2 3]
 [2 3 4]
 [5 6 7]]
<class 'numpy.ndarray'>

--------------Creating a 3-D array from a list of lists-------------

[[[1 2 4]
  [2 3 4]]

 [[1 2 4]
  [2 3 4]]]
<class 'numpy.ndarray'>

-------------array can be converted to any other valid data type------------

[[1. 2. 3.]
 [2. 3. 4.]
 [5. 6. 7.]]
<class 'numpy.ndarray'>

-------------NumPy tries to find a common datatype that can accommodate all the elements----------------

['a' '2.3' '5' '40000']

-------------If you want to maintain the original datatype , we can explicit specify the datatype-----------

['a' 2.3 5 40000]

-------------find the dimension of array----------------

Dimension of Array =  3

-------------find the shape of array----------------

Shape of Array =  (2, 2, 3)

----------The ndarray.dtype attribute in NumPy represents the datatype of the el